### ISSUE TITLE
"BlueBubbles server is not responding" Error

### ISSUE THREAD

**Issue by jhlee2222** [ngencokamin/sh-imessage-setup#11]
After a recent power failure, I had to restart everything, including BlueBubbles server and the bridge, deleting the old bridge via the script and creating it anew.

Everything worked great until it got the point of "Pinging BlueBubbles server at http://localhost:1234". After that, I receive the error "BlueBubbles server is not responding. Please make sure it's running and try again." However, BlueBubbles IS up and running. Client apps on both my Android phone and my Windows PC are receiving messages and connecting to the server without issue.

It's overall perplexing since nothing had changed. The bridge had worked just fine for a month or so prior to the extended power failure.

**Comment by cameronaaron** [comment]
Can you see if this version fixes it https://github.com/ngencokamin/sh-imessage-setup/tree/cameronaaron-patch-1

**Comment by ngencokamin** [comment]
> Hi, I actually just used this branch `https://github.com/ngencokamin/sh-imessage-setup/tree/fix/tmux-prereq-remove-install` and it seems to work fine.

that branch should be merged into main....

**Comment by ngencokamin** [comment]
> Yes, then I guess some thing else merged in main caused the issue. I only had the idea because the last time I had touched this great script was about 3/4 months ago and so I thought why not check if that code still worked on my computer. Idk why it works though. For context I'm running latest MacOS on M1 Mac Mini, and Full Private API BlueBubbles setup with defaults.

my mom is visiting me this weekend but when I have time I'll prolly bug you to try and debug and figure out what broke it!

**Comment by ngencokamin** [comment]
> Of course, if @jhlee2222 wants to do this they can just git clone the project and checkout that branch and then run everything as usual. Thank you so much for this wonderful code! It really has added so much to my life to be able to have everything in one place.

glad to help! can you please try @cameronaaron 's [PR](https://github.com/ngencokamin/sh-imessage-setup/pull/12) and see if that fixes your issue?

**Comment by ngencokamin** [comment]
> > glad to help! can you please try @cameronaaron 's [PR](https://github.com/ngencokamin/sh-imessage-setup/pull/12) and see if that fixes your issue?
> 
> Just tried the patch branch and it solves the issue! I believe this issue can be closed now. Maybe a record for a git issue.

Slay, I've merged the changes. Once you or @jhlee2222 confirms this fixed the issue on main I'll close the issue :)

**Comment by jhlee2222** [comment]
I just updated and ran it again. Problem solved. Thank you all so much for the quick action on this! I use my MacMini solely to have access to iMessage. It's a bit old. Any advice on increasing it's resilience is appreciated.
