### ISSUE TITLE
./setup.sh: line 232: tmux: command not found

### ISSUE THREAD

**Issue by jmcwheeler** [ngencokamin/sh-imessage-setup#6]
I've had my BlueBubbles server running without issue for months. I'm trying to use this to get my iMessage back into Beeper. Setup completes, but when I tell the setup to start the bridge now, I get the following error: ./setup.sh: line 232: tmux: command not found. Any suggestions?

**Comment by jasonlaguidice** [comment]
This script requires that you have [tmux ](https://github.com/tmux/tmux) installed. Try following their instructions to get that setup and working.

I opened a pull request to specify this requirement.

**Comment by ngencokamin** [comment]
> I've had my BlueBubbles server running without issue for months. I'm trying to use this to get my iMessage back into Beeper. Setup completes, but when I tell the setup to start the bridge now, I get the following error: ./setup.sh: line 232: tmux: command not found. Any suggestions?

Yep my bad, created #9 to address this in future installs

**Comment by cameronaaron** [comment]
Addressed in #9 and merged
